function createfigure(X1, YMatrix1, YMatrix2, X2, Y1)
%CREATEFIGURE(X1, YMatrix1, YMatrix2, X2, Y1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data
%  YMATRIX2:  matrix of plot y data
%  X2:  vector of plot x data
%  Y1:  vector of plot y data

%  Auto-generated by MATLAB on 04-Jun-2024 17:36:41

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(3,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1);
set(plot1(1),'DisplayName','$\psi_d$','LineWidth',1.2);
set(plot1(2),'DisplayName','$\psi(k)$','LineWidth',2.4);

% Create ylabel
ylabel('$\psi(k)$','Interpreter','latex');

% Create title
title({'Posicion Angular ','136.6'},'FontSize',24,'Interpreter','latex');

box(subplot1,'on');
grid(subplot1,'on');
hold(subplot1,'off');
% Set the remaining axes properties
set(subplot1,'FontSize',15);
% Create legend
legend1 = legend(subplot1,'show');
set(legend1,'Interpreter','latex','FontWeight','bold','FontSize',15);

% Create subplot
subplot2 = subplot(3,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple line objects using matrix input to plot
plot2 = plot(X1,YMatrix2,'Parent',subplot2,'LineWidth',2.4);
set(plot2(1),'DisplayName','$Kp$');
set(plot2(2),'DisplayName','$Kd$');
set(plot2(3),'DisplayName','$Ki$*0.00001');

% Create ylabel
ylabel('$K$','Interpreter','latex');

% Create title
title('Ganancias','FontSize',24,'Interpreter','latex');

box(subplot2,'on');
hold(subplot2,'off');
% Set the remaining axes properties
set(subplot2,'FontSize',14);
% Create legend
legend2 = legend(subplot2,'show');
set(legend2,'Interpreter','latex');

% Create subplot
subplot3 = subplot(3,1,3,'Parent',figure1);
hold(subplot3,'on');

% Create plot
plot(X2,Y1,'Parent',subplot3,'LineWidth',2.4);

% Create ylabel
ylabel('$deg$','Interpreter','latex');

% Create xlabel
xlabel('$k$','Interpreter','latex');

% Create title
title({'Error ','3.93'},'FontSize',24,'Interpreter','latex');

box(subplot3,'on');
hold(subplot3,'off');
% Set the remaining axes properties
set(subplot3,'FontSize',14);
